import {
  Activity, AlertCircle, AlertTriangle, Apple, ArrowDown, ArrowDownToLine, ArrowLeft,
  ArrowLeftRight, ArrowRight, ArrowUp, ArrowUpDown, Award,
  BarChart2, BarChart3, Bell, BellOff, Bike, BookOpen, Bookmark, Brain, Droplets,
  Building2, Calendar, CalendarPlus, CalendarRange, Camera, Check, CheckCircle2,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, ClipboardList,
  Clock, Compass, Copy, Crown, Download, Dumbbell, FileText, Flag, Flame, Footprints,
  GripVertical, Hammer, Heart, HeartPulse, HelpCircle, Home, Info, Layers,
  Leaf, Lightbulb, Link2, ListChecks, Lock, LogOut, Medal, MessageCircle, Minus,
  Moon, Mountain, MousePointerClick, Move, Palette, Pause, Pencil, PersonStanding,
  PartyPopper, Play, PlayCircle, Plus, RefreshCw, Repeat2, RotateCcw, Save, Scale, Search,
  Settings, Settings2, Shield, Shuffle, Skull, SlidersHorizontal, Snowflake, Sparkles,
  Star, Stethoscope, Target, ThumbsDown, ThumbsUp, Timer, Trash2, TrendingDown,
  TrendingUp, Trophy, TreePine, Sun, ImageIcon, Utensils, User, Watch, Waves, Wind, X, Zap,
  type LucideIcon,
} from 'lucide-react-native';

export type AppIconName =
  | 'activity' | 'alert-circle' | 'alert-triangle' | 'arrow-down' | 'arrow-down-to-line'
  | 'arrow-left' | 'arrow-left-right' | 'arrow-right' | 'arrow-up' | 'arrow-up-down'
  | 'award' | 'bar-chart'
  | 'bar-chart-3' | 'bell' | 'bell-off' | 'bike' | 'book-open' | 'bookmark' | 'brain' | 'building'
  | 'calendar' | 'calendar-plus' | 'calendar-range' | 'camera' | 'check' | 'check-circle'
  | 'chevron-down'
  | 'chevron-left' | 'chevron-right' | 'chevron-up' | 'circle' | 'clipboard-list'
  | 'clock' | 'compass' | 'copy' | 'crown' | 'download' | 'dumbbell' | 'file-text' | 'flag' | 'flame'
  | 'footprints' | 'grip-vertical' | 'hammer' | 'heart' | 'heart-pulse' | 'help-circle'
  | 'home' | 'info' | 'layers' | 'leaf' | 'lightbulb' | 'link' | 'list-checks' | 'lock'
  | 'log-out' | 'medal' | 'message-circle' | 'minus' | 'moon' | 'mountain' | 'mouse-pointer-click'
  | 'move' | 'palette' | 'pause' | 'pencil' | 'person-standing' | 'play' | 'play-circle'
  | 'plus' | 'refresh' | 'repeat' | 'rotate-ccw' | 'save' | 'scale' | 'search' | 'settings'
  | 'settings-2' | 'shield' | 'skull' | 'sliders-horizontal' | 'snowflake' | 'sparkles'
  | 'star' | 'stethoscope' | 'target' | 'thumbs-down' | 'thumbs-up' | 'timer' | 'trash'
  | 'droplets' | 'image' | 'sun' | 'tree-pine' | 'trending-down' | 'trending-up' | 'trophy'
  | 'apple' | 'party-popper' | 'shuffle' | 'user' | 'utensils' | 'watch' | 'waves' | 'wind' | 'x' | 'zap';

export const SF_SYMBOL_MAP: Record<AppIconName, string> = {
  'apple':                  'apple.logo',
  'bike':                   'bicycle',
  'droplets':               'drop',
  'image':                  'photo',
  'mountain':               'mountain.2',
  'sun':                    'sun.max',
  'tree-pine':              'tree',
  'utensils':               'fork.knife',
  'waves':                  'water.waves',
  'activity':               'waveform',
  'alert-circle':           'exclamationmark.circle',
  'alert-triangle':         'exclamationmark.triangle',
  'arrow-down':             'arrow.down',
  'arrow-down-to-line':     'arrow.down.to.line',
  'arrow-left':             'arrow.left',
  'arrow-left-right':       'arrow.left.arrow.right',
  'arrow-right':            'arrow.right',
  'arrow-up':               'arrow.up',
  'arrow-up-down':          'arrow.up.arrow.down',
  'award':                  'rosette',
  'bar-chart':              'chart.bar',
  'bar-chart-3':            'chart.bar.fill',
  'bell':                   'bell',
  'bell-off':               'bell.slash',
  'book-open':              'book',            // book.open not in SF Symbols
  'bookmark':               'bookmark',
  'brain':                  'brain',
  'building':               'building.2',
  'calendar':               'calendar',
  'calendar-plus':          'calendar.badge.plus',
  'calendar-range':         'calendar.badge.clock',
  'camera':                 'camera',
  'check':                  'checkmark',
  'check-circle':           'checkmark.circle',
  'chevron-down':           'chevron.down',
  'chevron-left':           'chevron.left',
  'chevron-right':          'chevron.right',
  'chevron-up':             'chevron.up',
  'circle':                 'circle',
  'clipboard-list':         'list.clipboard',
  'copy':                   'doc.on.doc',
  'clock':                  'clock',
  'compass':                'safari',
  'crown':                  'crown',
  'download':               'arrow.down.circle',
  'dumbbell':               'dumbbell',
  'file-text':              'doc.text',
  'flag':                   'flag',
  'flame':                  'flame',
  'footprints':             'figure.walk',
  'grip-vertical':          'line.3.horizontal',
  'hammer':                 'hammer',
  'heart':                  'heart',
  'heart-pulse':            'waveform.path.ecg',
  'help-circle':            'questionmark.circle',
  'home':                   'house',
  'info':                   'info.circle',
  'layers':                 'square.stack.3d.up',
  'leaf':                   'leaf',
  'lightbulb':              'lightbulb',
  'link':                   'link',
  'list-checks':            'checklist',
  'lock':                   'lock',
  'log-out':                'rectangle.portrait.and.arrow.right',
  'medal':                  'medal',
  'message-circle':         'message.circle',
  'minus':                  'minus',
  'moon':                   'moon',
  'mouse-pointer-click':    'hand.tap',
  'move':                   'arrow.up.down.left.right',
  'party-popper':           'party.popper',
  'palette':                'paintpalette',
  'pause':                  'pause',
  'pencil':                 'pencil',
  'person-standing':        'figure.stand',
  'play':                   'play',
  'play-circle':            'play.circle',
  'plus':                   'plus',
  'refresh':                'arrow.clockwise',
  'repeat':                 'repeat',
  'rotate-ccw':             'arrow.counterclockwise',
  'save':                   'square.and.arrow.down',
  'scale':                  'scalemass',
  'search':                 'magnifyingglass',
  'settings':               'gearshape',
  'settings-2':             'slider.horizontal.3',
  'shuffle':                'shuffle',
  'shield':                 'shield',
  'skull':                  'xmark.shield',
  'sliders-horizontal':     'slider.horizontal.3',
  'snowflake':              'snowflake',
  'sparkles':               'sparkles',
  'star':                   'star',
  'stethoscope':            'stethoscope',
  'target':                 'target',
  'thumbs-down':            'hand.thumbsdown',
  'thumbs-up':              'hand.thumbsup',
  'timer':                  'timer',
  'trash':                  'trash',
  'trending-down':          'chart.line.downtrend.xyaxis',
  'trending-up':            'chart.line.uptrend.xyaxis',
  'trophy':                 'trophy',
  'user':                   'person',
  'watch':                  'applewatch',
  'wind':                   'wind',
  'x':                      'xmark',
  'zap':                    'bolt',
};

export const LUCIDE_MAP: Record<AppIconName, LucideIcon> = {
  'apple':              Apple,
  'bike':               Bike,
  'droplets':           Droplets,
  'image':              ImageIcon,
  'mountain':           Mountain,
  'sun':                Sun,
  'tree-pine':          TreePine,
  'utensils':           Utensils,
  'waves':              Waves,
  'activity':           Activity,
  'alert-circle':       AlertCircle,
  'alert-triangle':     AlertTriangle,
  'arrow-down':         ArrowDown,
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-left':         ArrowLeft,
  'arrow-left-right':   ArrowLeftRight,
  'arrow-right':        ArrowRight,
  'arrow-up':           ArrowUp,
  'arrow-up-down':      ArrowUpDown,
  'award':              Award,
  'bar-chart':          BarChart2,
  'bar-chart-3':        BarChart3,
  'bell':               Bell,
  'bell-off':           BellOff,
  'book-open':          BookOpen,
  'bookmark':           Bookmark,
  'brain':              Brain,
  'building':           Building2,
  'calendar':           Calendar,
  'calendar-plus':      CalendarPlus,
  'calendar-range':     CalendarRange,
  'camera':             Camera,
  'check':              Check,
  'check-circle':       CheckCircle2,
  'chevron-down':       ChevronDown,
  'chevron-left':       ChevronLeft,
  'chevron-right':      ChevronRight,
  'chevron-up':         ChevronUp,
  'circle':             Circle,
  'clipboard-list':     ClipboardList,
  'copy':               Copy,
  'clock':              Clock,
  'compass':            Compass,
  'crown':              Crown,
  'download':           Download,
  'dumbbell':           Dumbbell,
  'file-text':          FileText,
  'flag':               Flag,
  'flame':              Flame,
  'footprints':         Footprints,
  'grip-vertical':      GripVertical,
  'hammer':             Hammer,
  'heart':              Heart,
  'heart-pulse':        HeartPulse,
  'help-circle':        HelpCircle,
  'home':               Home,
  'info':               Info,
  'layers':             Layers,
  'leaf':               Leaf,
  'lightbulb':          Lightbulb,
  'link':               Link2,
  'list-checks':        ListChecks,
  'lock':               Lock,
  'log-out':            LogOut,
  'medal':              Medal,
  'message-circle':     MessageCircle,
  'minus':              Minus,
  'moon':               Moon,
  'mouse-pointer-click': MousePointerClick,
  'move':               Move,
  'party-popper':       PartyPopper,
  'palette':            Palette,
  'pause':              Pause,
  'pencil':             Pencil,
  'person-standing':    PersonStanding,
  'play':               Play,
  'play-circle':        PlayCircle,
  'plus':               Plus,
  'refresh':            RefreshCw,
  'repeat':             Repeat2,
  'rotate-ccw':         RotateCcw,
  'save':               Save,
  'scale':              Scale,
  'search':             Search,
  'settings':           Settings,
  'settings-2':         Settings2,
  'shuffle':            Shuffle,
  'shield':             Shield,
  'skull':              Skull,
  'sliders-horizontal': SlidersHorizontal,
  'snowflake':          Snowflake,
  'sparkles':           Sparkles,
  'star':               Star,
  'stethoscope':        Stethoscope,
  'target':             Target,
  'thumbs-down':        ThumbsDown,
  'thumbs-up':          ThumbsUp,
  'timer':              Timer,
  'trash':              Trash2,
  'trending-down':      TrendingDown,
  'trending-up':        TrendingUp,
  'trophy':             Trophy,
  'user':               User,
  'watch':              Watch,
  'wind':               Wind,
  'x':                  X,
  'zap':                Zap,
};
