#!/usr/bin/env node
/**
 * Adds 12 new exercises to exerciseSchema.json (v1.5)
 */

const fs = require('fs');
const path = require('path');

const schemaPath = path.join(__dirname, '..', 'mocks', 'exerciseSchema.json');
const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf-8'));

const ZERO_LOAD = {
  male_beginner:     { multiplier: 0, absolute_fallback_lbs: 0 },
  male_intermediate: { multiplier: 0, absolute_fallback_lbs: 0 },
  male_advanced:     { multiplier: 0, absolute_fallback_lbs: 0 },
  female_beginner:   { multiplier: 0, absolute_fallback_lbs: 0 },
  female_intermediate:{ multiplier: 0, absolute_fallback_lbs: 0 },
  female_advanced:   { multiplier: 0, absolute_fallback_lbs: 0 },
};

const newExercises = [
  // ═══════════════════════════════════════════════════════
  // 1. CHEST-TO-BAR PULL-UP
  // ═══════════════════════════════════════════════════════
  {
    id: 'chest_to_bar_pull_up',
    name: 'Chest-to-Bar Pull-Up',
    aliases: ['C2B', 'c2b pull-up', 'chest to bar'],
    movement_pattern: 'pull',
    difficulty_tier: 'advanced',
    eligible_styles: ['crossfit', 'hybrid'],
    primary_muscles: ['lats', 'upper_back'],
    secondary_muscles: ['biceps', 'rear_delt', 'core', 'forearms'],
    joints_loaded: ['shoulder', 'elbow'],
    equipment_required: ['pull_up_bar'],
    equipment_optional: [],
    is_unilateral: false,
    is_compound: true,
    default_tempo_seconds_per_rep: 3,
    setup_time_seconds: 10,
    contraindication_tags: ['shoulder_injury', 'shoulder_impingement', 'elbow_injury', 'wrist_injury'],
    rom_requirement: 'full',
    spinal_load: 'none',
    position: 'hanging',
    weight_increment: 0,
    rep_range_floor: 3,
    rep_range_ceiling: 15,
    default_load_table: ZERO_LOAD,
    is_warmup_eligible: false,
    is_cooldown_eligible: false,
    warmup_for_muscles: [],
    cooldown_for_muscles: [],
    substitutes: ['pull_up', 'lat_pulldown', 'inverted_row'],
    variation_family: 'pull_up_family',
    style_popularity: { crossfit: 80, hybrid: 40 },
    tracking_metric: { primary: 'reps', alternates: [] },
    execution_logic: 'bilateral',
    default_rest_sec: 90,
    standard_rx_weight: null,
    media_url: '',
  },

  // ═══════════════════════════════════════════════════════
  // 2. HANDSTAND WALK
  // ═══════════════════════════════════════════════════════
  {
    id: 'handstand_walk',
    name: 'Handstand Walk',
    aliases: ['HS walk', 'handstand walking'],
    movement_pattern: 'push',
    difficulty_tier: 'advanced',
    eligible_styles: ['crossfit'],
    primary_muscles: ['front_delt', 'side_delt'],
    secondary_muscles: ['triceps', 'core', 'traps', 'upper_back'],
    joints_loaded: ['shoulder', 'wrist', 'elbow'],
    equipment_required: ['bodyweight'],
    equipment_optional: [],
    is_unilateral: false,
    is_compound: true,
    default_tempo_seconds_per_rep: 3,
    setup_time_seconds: 10,
    contraindication_tags: ['shoulder_injury', 'shoulder_impingement', 'wrist_injury', 'high_blood_pressure', 'neck_injury', 'pregnancy_t1', 'pregnancy_t2', 'pregnancy_t3'],
    rom_requirement: 'full',
    spinal_load: 'moderate',
    position: 'hanging',
    weight_increment: 0,
    rep_range_floor: 5,
    rep_range_ceiling: 50,
    default_load_table: ZERO_LOAD,
    is_warmup_eligible: false,
    is_cooldown_eligible: false,
    warmup_for_muscles: [],
    cooldown_for_muscles: [],
    substitutes: ['handstand_push_up', 'pike_push_up', 'standing_overhead_press'],
    variation_family: 'handstand_family',
    style_popularity: { crossfit: 55 },
    tracking_metric: { primary: 'distance_meters', alternates: ['reps'] },
    execution_logic: 'bilateral',
    default_rest_sec: 90,
    standard_rx_weight: null,
    media_url: '',
  },

  // ═══════════════════════════════════════════════════════
  // 3. SPLIT JERK
  // ═══════════════════════════════════════════════════════
  {
    id: 'split_jerk',
    name: 'Split Jerk',
    aliases: ['jerk', 'barbell split jerk'],
    movement_pattern: 'push',
    difficulty_tier: 'advanced',
    eligible_styles: ['crossfit', 'strength', 'hybrid'],
    primary_muscles: ['front_delt', 'quads', 'glutes'],
    secondary_muscles: ['triceps', 'core', 'hip_flexors', 'calves'],
    joints_loaded: ['shoulder', 'elbow', 'hip', 'knee', 'ankle'],
    equipment_required: ['barbell', 'squat_rack'],
    equipment_optional: [],
    is_unilateral: false,
    is_compound: true,
    default_tempo_seconds_per_rep: 4,
    setup_time_seconds: 30,
    contraindication_tags: ['shoulder_injury', 'shoulder_impingement', 'overhead_restricted', 'knee_injury', 'ankle_injury', 'lower_back_injury', 'wrist_injury', 'pregnancy_t2', 'pregnancy_t3'],
    rom_requirement: 'full',
    spinal_load: 'heavy',
    position: 'standing',
    weight_increment: 5,
    rep_range_floor: 1,
    rep_range_ceiling: 5,
    default_load_table: {
      male_beginner:     { multiplier: 0.35, absolute_fallback_lbs: 65 },
      male_intermediate: { multiplier: 0.55, absolute_fallback_lbs: 115 },
      male_advanced:     { multiplier: 0.75, absolute_fallback_lbs: 165 },
      female_beginner:   { multiplier: 0.25, absolute_fallback_lbs: 45 },
      female_intermediate:{ multiplier: 0.4, absolute_fallback_lbs: 75 },
      female_advanced:   { multiplier: 0.6, absolute_fallback_lbs: 115 },
    },
    is_warmup_eligible: false,
    is_cooldown_eligible: false,
    warmup_for_muscles: [],
    cooldown_for_muscles: [],
    substitutes: ['clean_and_jerk', 'standing_overhead_press', 'push_press'],
    variation_family: 'jerk_family',
    style_popularity: { crossfit: 70, strength: 30, hybrid: 45 },
    tracking_metric: { primary: 'reps', alternates: [] },
    execution_logic: 'bilateral',
    default_rest_sec: 150,
    standard_rx_weight: { male_rx_lbs: 135, female_rx_lbs: 95, male_scaled_lbs: 95, female_scaled_lbs: 65, male_pro_lbs: 185, female_pro_lbs: 135 },
    media_url: '',
  },

  // ═══════════════════════════════════════════════════════
  // 4. DUMBBELL HANG CLEAN & JERK
  // ═══════════════════════════════════════════════════════
  {
    id: 'dumbbell_hang_clean_and_jerk',
    name: 'DB Hang Clean & Jerk',
    aliases: ['dumbbell hang clean and jerk', 'db hang c&j', 'single arm db clean and jerk'],
    movement_pattern: 'push',
    difficulty_tier: 'intermediate',
    eligible_styles: ['crossfit', 'hiit', 'hybrid'],
    primary_muscles: ['front_delt', 'quads', 'glutes'],
    secondary_muscles: ['triceps', 'core', 'hamstrings', 'traps', 'forearms'],
    joints_loaded: ['shoulder', 'elbow', 'hip', 'knee', 'wrist'],
    equipment_required: ['dumbbell'],
    equipment_optional: [],
    is_unilateral: true,
    is_compound: true,
    default_tempo_seconds_per_rep: 4,
    setup_time_seconds: 10,
    contraindication_tags: ['shoulder_injury', 'shoulder_impingement', 'overhead_restricted', 'lower_back_injury', 'wrist_injury', 'pregnancy_t2', 'pregnancy_t3'],
    rom_requirement: 'full',
    spinal_load: 'moderate',
    position: 'standing',
    weight_increment: 5,
    rep_range_floor: 5,
    rep_range_ceiling: 15,
    default_load_table: {
      male_beginner:     { multiplier: 0, absolute_fallback_lbs: 25 },
      male_intermediate: { multiplier: 0, absolute_fallback_lbs: 40 },
      male_advanced:     { multiplier: 0, absolute_fallback_lbs: 55 },
      female_beginner:   { multiplier: 0, absolute_fallback_lbs: 15 },
      female_intermediate:{ multiplier: 0, absolute_fallback_lbs: 25 },
      female_advanced:   { multiplier: 0, absolute_fallback_lbs: 40 },
    },
    is_warmup_eligible: false,
    is_cooldown_eligible: false,
    warmup_for_muscles: [],
    cooldown_for_muscles: [],
    substitutes: ['dumbbell_snatch', 'dumbbell_clean_and_press', 'dumbbell_power_clean'],
    variation_family: 'db_olympic_family',
    style_popularity: { crossfit: 75, hiit: 35, hybrid: 50 },
    tracking_metric: { primary: 'reps', alternates: [] },
    execution_logic: 'alternating',
    default_rest_sec: 90,
    standard_rx_weight: { male_rx_lbs: 50, female_rx_lbs: 35, male_scaled_lbs: 35, female_scaled_lbs: 20, male_pro_lbs: 70, female_pro_lbs: 50 },
    media_url: '',
  },

  // ═══════════════════════════════════════════════════════
  // 5. OUTDOOR RUN
  // ═══════════════════════════════════════════════════════
  {
    id: 'outdoor_run',
    name: 'Outdoor Run',
    aliases: ['track run', 'road run', 'outdoor jog', 'trail run'],
    movement_pattern: 'cardio',
    difficulty_tier: 'beginner',
    eligible_styles: ['cardio', 'hiit', 'hyrox', 'hybrid'],
    primary_muscles: ['quads', 'hamstrings', 'calves', 'glutes'],
    secondary_muscles: ['core', 'hip_flexors'],
    joints_loaded: ['hip', 'knee', 'ankle'],
    equipment_required: ['bodyweight'],
    equipment_optional: [],
    is_unilateral: false,
    is_compound: true,
    default_tempo_seconds_per_rep: 60,
    setup_time_seconds: 5,
    contraindication_tags: ['knee_injury', 'ankle_injury', 'acl_tear', 'pregnancy_t3', 'hip_replacement'],
    rom_requirement: 'moderate',
    spinal_load: 'light',
    position: 'standing',
    weight_increment: 0,
    rep_range_floor: 400,
    rep_range_ceiling: 5000,
    default_load_table: ZERO_LOAD,
    is_warmup_eligible: true,
    is_cooldown_eligible: true,
    warmup_for_muscles: ['quads', 'hamstrings', 'calves', 'glutes'],
    cooldown_for_muscles: ['quads', 'hamstrings', 'calves'],
    substitutes: ['treadmill_run', 'rowing_machine_intervals', 'assault_bike_intervals'],
    variation_family: 'running_family',
    style_popularity: { cardio: 85, hiit: 45, hyrox: 80, hybrid: 65 },
    tracking_metric: { primary: 'distance_meters', alternates: ['time_seconds', 'calories'] },
    execution_logic: 'bilateral',
    default_rest_sec: 60,
    standard_rx_weight: null,
    media_url: '',
  },

  // ═══════════════════════════════════════════════════════
  // 6. RUCKING
  // ═══════════════════════════════════════════════════════
  {
    id: 'rucking',
    name: 'Rucking',
    aliases: ['weighted walk', 'ruck march', 'ruck walk', 'weighted ruck'],
    movement_pattern: 'carry',
    difficulty_tier: 'beginner',
    eligible_styles: ['hybrid', 'low_impact', 'hyrox', 'cardio'],
    primary_muscles: ['quads', 'hamstrings', 'glutes', 'calves'],
    secondary_muscles: ['core', 'traps', 'lower_back', 'hip_flexors'],
    joints_loaded: ['hip', 'knee', 'ankle', 'spine'],
    equipment_required: ['bodyweight'],
    equipment_optional: ['weight_plates'],
    is_unilateral: false,
    is_compound: true,
    default_tempo_seconds_per_rep: 60,
    setup_time_seconds: 15,
    contraindication_tags: ['knee_injury', 'ankle_injury', 'lower_back_injury', 'hip_replacement'],
    rom_requirement: 'moderate',
    spinal_load: 'moderate',
    position: 'standing',
    weight_increment: 0,
    rep_range_floor: 400,
    rep_range_ceiling: 5000,
    default_load_table: ZERO_LOAD,
    is_warmup_eligible: false,
    is_cooldown_eligible: true,
    warmup_for_muscles: [],
    cooldown_for_muscles: ['quads', 'hamstrings', 'calves'],
    substitutes: ['farmers_carry', 'outdoor_run', 'treadmill_run'],
    variation_family: 'rucking_family',
    style_popularity: { hybrid: 60, low_impact: 50, hyrox: 45, cardio: 40 },
    tracking_metric: { primary: 'distance_meters', alternates: ['time_seconds'] },
    execution_logic: 'bilateral',
    default_rest_sec: 60,
    standard_rx_weight: null,
    media_url: '',
  },

  // ═══════════════════════════════════════════════════════
  // 7. CALORIE ROW
  // ═══════════════════════════════════════════════════════
  {
    id: 'calorie_row',
    name: 'Calorie Row',
    aliases: ['cal row', 'row for calories', 'rowing calories'],
    movement_pattern: 'cardio',
    difficulty_tier: 'beginner',
    eligible_styles: ['crossfit', 'hybrid', 'hiit'],
    primary_muscles: ['lats', 'upper_back', 'quads'],
    secondary_muscles: ['biceps', 'hamstrings', 'glutes', 'core', 'forearms'],
    joints_loaded: ['shoulder', 'elbow', 'hip', 'knee'],
    equipment_required: ['rowing_machine'],
    equipment_optional: [],
    is_unilateral: false,
    is_compound: true,
    default_tempo_seconds_per_rep: 4,
    setup_time_seconds: 10,
    contraindication_tags: ['lower_back_injury', 'shoulder_injury'],
    rom_requirement: 'moderate',
    spinal_load: 'light',
    position: 'seated',
    weight_increment: 0,
    rep_range_floor: 10,
    rep_range_ceiling: 30,
    default_load_table: ZERO_LOAD,
    is_warmup_eligible: true,
    is_cooldown_eligible: false,
    warmup_for_muscles: ['lats', 'upper_back', 'quads'],
    cooldown_for_muscles: [],
    substitutes: ['rowing_machine_intervals', 'calorie_assault_bike', 'calorie_ski_erg'],
    variation_family: 'rowing_family',
    style_popularity: { crossfit: 80, hybrid: 55, hiit: 45 },
    tracking_metric: { primary: 'calories', alternates: ['distance_meters', 'time_seconds'] },
    execution_logic: 'bilateral',
    default_rest_sec: 60,
    standard_rx_weight: null,
    media_url: '',
  },

  // ═══════════════════════════════════════════════════════
  // 8. CALORIE ASSAULT BIKE
  // ═══════════════════════════════════════════════════════
  {
    id: 'calorie_assault_bike',
    name: 'Calorie Assault Bike',
    aliases: ['cal bike', 'assault bike calories', 'echo bike calories', 'air bike calories'],
    movement_pattern: 'cardio',
    difficulty_tier: 'beginner',
    eligible_styles: ['crossfit', 'hybrid', 'hiit'],
    primary_muscles: ['quads', 'hamstrings', 'glutes'],
    secondary_muscles: ['core', 'front_delt', 'biceps', 'triceps', 'calves'],
    joints_loaded: ['hip', 'knee', 'shoulder'],
    equipment_required: ['assault_bike'],
    equipment_optional: [],
    is_unilateral: false,
    is_compound: true,
    default_tempo_seconds_per_rep: 4,
    setup_time_seconds: 10,
    contraindication_tags: ['knee_injury'],
    rom_requirement: 'moderate',
    spinal_load: 'none',
    position: 'seated',
    weight_increment: 0,
    rep_range_floor: 10,
    rep_range_ceiling: 30,
    default_load_table: ZERO_LOAD,
    is_warmup_eligible: true,
    is_cooldown_eligible: false,
    warmup_for_muscles: ['quads', 'hamstrings'],
    cooldown_for_muscles: [],
    substitutes: ['assault_bike_intervals', 'calorie_row', 'calorie_ski_erg'],
    variation_family: 'assault_bike_family',
    style_popularity: { crossfit: 75, hybrid: 50, hiit: 50 },
    tracking_metric: { primary: 'calories', alternates: ['time_seconds'] },
    execution_logic: 'bilateral',
    default_rest_sec: 60,
    standard_rx_weight: null,
    media_url: '',
  },

  // ═══════════════════════════════════════════════════════
  // 9. CALORIE SKI ERG
  // ═══════════════════════════════════════════════════════
  {
    id: 'calorie_ski_erg',
    name: 'Calorie Ski Erg',
    aliases: ['cal ski', 'ski erg calories', 'ski for calories'],
    movement_pattern: 'cardio',
    difficulty_tier: 'beginner',
    eligible_styles: ['crossfit', 'hybrid', 'hiit'],
    primary_muscles: ['lats', 'triceps', 'core'],
    secondary_muscles: ['front_delt', 'upper_back', 'quads', 'glutes'],
    joints_loaded: ['shoulder', 'elbow', 'hip'],
    equipment_required: ['ski_erg'],
    equipment_optional: [],
    is_unilateral: false,
    is_compound: true,
    default_tempo_seconds_per_rep: 4,
    setup_time_seconds: 10,
    contraindication_tags: ['shoulder_injury'],
    rom_requirement: 'moderate',
    spinal_load: 'light',
    position: 'standing',
    weight_increment: 0,
    rep_range_floor: 10,
    rep_range_ceiling: 30,
    default_load_table: ZERO_LOAD,
    is_warmup_eligible: true,
    is_cooldown_eligible: false,
    warmup_for_muscles: ['lats', 'triceps', 'core'],
    cooldown_for_muscles: [],
    substitutes: ['ski_erg_intervals', 'calorie_row', 'calorie_assault_bike'],
    variation_family: 'ski_erg_family',
    style_popularity: { crossfit: 65, hybrid: 45, hiit: 40 },
    tracking_metric: { primary: 'calories', alternates: ['distance_meters', 'time_seconds'] },
    execution_logic: 'bilateral',
    default_rest_sec: 60,
    standard_rx_weight: null,
    media_url: '',
  },

  // ═══════════════════════════════════════════════════════
  // 10. NORDIC HAMSTRING CURL
  // ═══════════════════════════════════════════════════════
  {
    id: 'nordic_hamstring_curl',
    name: 'Nordic Hamstring Curl',
    aliases: ['nordic curl', 'NHC', 'nordic ham curl', 'russian ham curl'],
    movement_pattern: 'isolation',
    difficulty_tier: 'intermediate',
    eligible_styles: ['strength', 'bodybuilding', 'hybrid'],
    primary_muscles: ['hamstrings'],
    secondary_muscles: ['glutes', 'calves', 'core'],
    joints_loaded: ['knee'],
    equipment_required: ['bodyweight'],
    equipment_optional: ['flat_bench'],
    is_unilateral: false,
    is_compound: false,
    default_tempo_seconds_per_rep: 5,
    setup_time_seconds: 15,
    contraindication_tags: ['knee_injury', 'acl_tear'],
    rom_requirement: 'full',
    spinal_load: 'none',
    position: 'kneeling',
    weight_increment: 0,
    rep_range_floor: 3,
    rep_range_ceiling: 12,
    default_load_table: ZERO_LOAD,
    is_warmup_eligible: false,
    is_cooldown_eligible: false,
    warmup_for_muscles: [],
    cooldown_for_muscles: [],
    substitutes: ['leg_curl', 'romanian_deadlift', 'glute_ham_raise'],
    variation_family: 'hamstring_curl_family',
    style_popularity: { strength: 50, bodybuilding: 55, hybrid: 45 },
    tracking_metric: { primary: 'reps', alternates: [] },
    execution_logic: 'bilateral',
    default_rest_sec: 90,
    standard_rx_weight: null,
    media_url: '',
  },

  // ═══════════════════════════════════════════════════════
  // 11. SCAPULAR PULL-UP
  // ═══════════════════════════════════════════════════════
  {
    id: 'scapular_pull_up',
    name: 'Scapular Pull-Up',
    aliases: ['scap pull-up', 'scapula pull-up', 'scap retraction hang'],
    movement_pattern: 'pull',
    difficulty_tier: 'beginner',
    eligible_styles: ['mobility', 'crossfit', 'strength', 'hybrid'],
    primary_muscles: ['lats', 'lower_back'],
    secondary_muscles: ['rhomboids', 'traps', 'rear_delt'],
    joints_loaded: ['shoulder'],
    equipment_required: ['pull_up_bar'],
    equipment_optional: [],
    is_unilateral: false,
    is_compound: false,
    default_tempo_seconds_per_rep: 4,
    setup_time_seconds: 10,
    contraindication_tags: ['shoulder_injury', 'shoulder_impingement'],
    rom_requirement: 'minimal',
    spinal_load: 'none',
    position: 'hanging',
    weight_increment: 0,
    rep_range_floor: 8,
    rep_range_ceiling: 20,
    default_load_table: ZERO_LOAD,
    is_warmup_eligible: true,
    is_cooldown_eligible: false,
    warmup_for_muscles: ['lats', 'upper_back', 'rear_delt', 'rhomboids'],
    cooldown_for_muscles: [],
    substitutes: ['band_pull_apart', 'face_pull', 'inverted_row'],
    variation_family: 'scap_activation_family',
    style_popularity: { mobility: 60, crossfit: 35, strength: 25, hybrid: 30 },
    tracking_metric: { primary: 'reps', alternates: [] },
    execution_logic: 'bilateral',
    default_rest_sec: 30,
    standard_rx_weight: null,
    media_url: '',
  },

  // ═══════════════════════════════════════════════════════
  // 12. SCAPULAR PUSH-UP
  // ═══════════════════════════════════════════════════════
  {
    id: 'scapular_push_up',
    name: 'Scapular Push-Up',
    aliases: ['scap push-up', 'scapula push-up', 'serratus push-up', 'push-up plus'],
    movement_pattern: 'push',
    difficulty_tier: 'beginner',
    eligible_styles: ['mobility', 'crossfit', 'strength', 'hybrid'],
    primary_muscles: ['front_delt', 'chest'],
    secondary_muscles: ['core', 'triceps'],
    joints_loaded: ['shoulder', 'wrist'],
    equipment_required: ['bodyweight'],
    equipment_optional: [],
    is_unilateral: false,
    is_compound: false,
    default_tempo_seconds_per_rep: 4,
    setup_time_seconds: 5,
    contraindication_tags: ['shoulder_injury', 'wrist_injury'],
    rom_requirement: 'minimal',
    spinal_load: 'none',
    position: 'prone',
    weight_increment: 0,
    rep_range_floor: 10,
    rep_range_ceiling: 20,
    default_load_table: ZERO_LOAD,
    is_warmup_eligible: true,
    is_cooldown_eligible: false,
    warmup_for_muscles: ['front_delt', 'chest', 'core'],
    cooldown_for_muscles: [],
    substitutes: ['scapular_pull_up', 'band_pull_apart', 'push_up'],
    variation_family: 'scap_activation_family',
    style_popularity: { mobility: 55, crossfit: 30, strength: 20, hybrid: 25 },
    tracking_metric: { primary: 'reps', alternates: [] },
    execution_logic: 'bilateral',
    default_rest_sec: 30,
    standard_rx_weight: null,
    media_url: '',
  },
];

// Validate no duplicate IDs
const existingIds = new Set(schema.exercises.map(e => e.id));
const dupes = newExercises.filter(e => existingIds.has(e.id));
if (dupes.length > 0) {
  console.error('DUPLICATE IDs found:', dupes.map(e => e.id).join(', '));
  process.exit(1);
}

// Validate all required fields present (35 total)
const requiredKeys = Object.keys(schema.exercises[0]);
for (const ex of newExercises) {
  const missing = requiredKeys.filter(k => !(k in ex));
  if (missing.length > 0) {
    console.error(`Exercise ${ex.id} missing fields: ${missing.join(', ')}`);
    process.exit(1);
  }
}

// Add exercises
schema.exercises.push(...newExercises);

// Write back
fs.writeFileSync(schemaPath, JSON.stringify(schema, null, 2) + '\n');

console.log(`\n✅ Added ${newExercises.length} new exercises (total: ${schema.exercises.length})`);
console.log('\nNew exercises:');
for (const ex of newExercises) {
  console.log(`  ${ex.id}: ${ex.name} [${ex.eligible_styles.join(', ')}] metric=${ex.tracking_metric.primary}`);
}
